# module

In [ ]:
import math
print(math.sqrt(25))
print(math.pi)

5.0
3.141592653589793


In [ ]:
import random

print(random.randint(1, 10))
print(random.choice(['red', 'green', 'blue']))


3
blue


In [ ]:
import datetime

now = datetime.datetime.now()
print(now)
print(now.year, now.month)


2025-07-07 19:32:52.432196
2025 7


In [ ]:
import json

data = '{"name": "Ali", "age": 25}'
parsed = json.loads(data)
print(parsed['name'])  # Ali


Ali


my modul

In [ ]:
module_code = """
def say_hello(name):
    return f"Hello, {name}!"

def add_numbers(a, b):
    return a + b
"""


with open("my_module.py", "w") as f:
    f.write(module_code)




# def say_hello(name):
#     return f"Hello, {name}!"

# def add_numbers(a, b):
#     return a + b



In [ ]:
import my_module

print(my_module.say_hello("dai"))
print(my_module.add_numbers(5, 7))


Hello, dai!
12


# numpy

In [ ]:
# import numpy    Numerical Python

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # numpy.ndarray


[1 2 3 4 5]
<class 'numpy.ndarray'>


**list vs array**

In [ ]:
list1 = [1, 2, 3]
print(list1 * 2)
arr1 = np.array([1, 2, 3])
print(arr1 * 2)


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print(arr.size)


(2, 3)
6


In [ ]:
arr = np.array([10, 20, 30])

print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))


20.0
10
30
60


In [ ]:
arr = np.array([5, 10, 15, 20, 25])

print(arr[0])      # 5
print(arr[1:4])    # [10 15 20]


5
[10 15 20]


# 2D array

In [ ]:

temps = np.array([
    [30, 32, 31],
    [28, 29, 27],
    [35, 36, 34]
])


print(np.mean(temps, axis=1))


print(np.mean(temps, axis=0))


[31. 28. 35.]
[31.         32.33333333 30.66666667]


# task

Using NumPy, build a small program to analyze sales data.

You are given a NumPy array of daily sales for a week (7 days).

Tasks:
Create a NumPy array that contains the sales data:
[1500, 2300, 1800, 0, 2700, 3000, 2000]

Print:

The total sales for the week

The average daily sales

The day(s) with the highest sales

The number of days with sales above 2000

The number of days with no sales

Replace all sales equal to 0 with the average of the week and print the new array.

In [ ]:
import numpy as np


sales = np.array([1500, 2300, 1800, 0, 2700, 3000, 2000])


total_sales = np.sum(sales)
average_sales = np.mean(sales)
max_sales = np.max(sales)
days_with_max = np.where(sales == max_sales)[0]
days_above_2000 = np.sum(sales > 2000)
days_with_zero = np.sum(sales == 0)


updated_sales = sales.copy()
updated_sales[updated_sales == 0] = average_sales


print("Original sales:", sales)
print("Total sales:", total_sales)
print("Average sales:", average_sales)
print("Highest sales:", max_sales)
print("Day(s) with highest sales (index):", days_with_max)
print("Number of days with sales > 2000:", days_above_2000)
print("Number of days with 0 sales:", days_with_zero)
print("Updated sales array:", updated_sales)


Analyze temperature data for 5 cities over 7 days using NumPy.

You are given a 2D NumPy array representing daily temperatures (in Celsius) for 5 cities over 7 days. Each row represents a city, and each column is a day.
Print:

The average temperature for each city.

The average temperature for each day.

The hottest day in each city.

The overall highest temperature and the city/day where it happened.

Number of days where any city's temperature was below 20°C.

In [ ]:
import numpy as np

temps = np.array([
    [30, 32, 33, 31, 29, 28, 30],
    [25, 26, 27, 28, 29, 30, 31],
    [20, 22, 23, 21, 24, 25, 26],
    [35, 34, 33, 32, 31, 30, 29],
    [15, 17, 18, 19, 20, 22, 23]
])

# 1. Average temperature for each city (row-wise)
avg_per_city = np.mean(temps, axis=1)

# 2. Average temperature for each day (column-wise)
avg_per_day = np.mean(temps, axis=0)

# 3. Hottest day in each city
hottest_per_city = np.max(temps, axis=1)

# 4. Overall highest temperature + location
overall_max = np.max(temps)
city_idx, day_idx = np.where(temps == overall_max)

# 5. Count of days with any city below 20
below_20 = temps < 20
days_with_below_20 = np.sum(np.any(below_20, axis=0))

# Print results
print("Average per city:", avg_per_city)
print("Average per day:", avg_per_day)
print("Hottest per city:", hottest_per_city)
print(f"Overall highest temp: {overall_max} at city {city_idx[0]}, day {day_idx[0]}")
print("Number of days with any city < 20°C:", days_with_below_20)
